include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    riverpod_lint: 3.0.3
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    prefer_single_quotes: true
